package MedianFinder;

public class Solution {

    public static void main(String [] args) {
        MedianFinder medianFinder = new MedianFinder();
       /* medianFinder.addNum(1);
        medianFinder.addNum(2);
        double median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(3);
        median = medianFinder.findMedian();
        System.out.println(median);*/
        /*medianFinder.addNum(-1);
        double median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(-2);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(-3);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(-4);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(-5);
        median = medianFinder.findMedian();
        System.out.println(median);*/

        medianFinder.addNum(40);
        double median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(12);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(16);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(14);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(35);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(19);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(34);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(35);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(28);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(35);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(26);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(6);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(8);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(2);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(14);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(25);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(25);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(4);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(33);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(18);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(10);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(14);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(27);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(3);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(35);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(13);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(24);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(27);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(14);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(5);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(0);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(38);
        median = medianFinder.findMedian();
        System.out.println(median);
        medianFinder.addNum(19);
        median = medianFinder.findMedian();
        System.out.println(median);
    }
}
